/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dividendSol from "./dividend.sol";
export type { dividendSol };
import type * as factorySol from "./factory.sol";
export type { factorySol };
import type * as interface from "./interface";
export type { interface };
import type * as mock from "./mock";
export type { mock };
import type * as upgradeability from "./upgradeability";
export type { upgradeability };
export type { XegaraNFT } from "./XegaraNFT";
