/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDividend__factory } from "./IDividend__factory";
export { IFactory__factory } from "./IFactory__factory";
export { IXegaraNFT__factory } from "./IXegaraNFT__factory";
