/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDividend } from "./IDividend";
export type { IFactory } from "./IFactory";
export type { IXegaraNFT } from "./IXegaraNFT";
