/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as dividendSol from "./dividend.sol";
export * as factorySol from "./factory.sol";
export * as interface from "./interface";
export * as mock from "./mock";
export * as upgradeability from "./upgradeability";
export { XegaraNFT__factory } from "./XegaraNFT__factory";
